# Generated by Django 3.0.6 on 2021-07-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cust_admin', '0002_auto_20210716_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_list',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
