# Generated by Django 3.0.6 on 2021-07-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cust_admin', '0003_auto_20210716_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_list',
            name='app_id',
            field=models.IntegerField(null=True),
        ),
    ]
