# Generated by Django 3.0.6 on 2021-07-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cust_admin', '0004_user_list_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_list',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
